<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class File extends Model
{
    protected $fillable = [
        'fileable_id', 'fileable_type', 'type_file_id', 'config'
    ];

    public function fileable() {
        return $this->morphTo();
    }

  public function typeFile() {
    return $this->belongsTo('App\TypeFile');
  }

  protected $casts = [
    'config' => 'array',
  ];

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub

    static::deleting(function($file) {
      $full_size_dir = storage_path('app/public/');
      $fileDir = $full_size_dir.$file->config['filename'];
      unlink($fileDir);
    });
  }
}